apiVersion: v1 
kind: Pod
metadata:
  name: nginx
  labels:
    tier: nginx
spec:
  containers:
    - name: nginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In 
                values:
                  - "ssd"