apiVersion: v1
kind: Pod
metadata:
  name: resources-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "250m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "128Mi"
