apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bmk-pod
  name: bmk-pod
spec:
  serviceAccountName: bmk-sa
  automountServiceAccountToken: false
  containers:
    - image: nginx
      name: bmk-pod
