apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: ADSFASDFASDF #To generate secret use the below comands
  DB_NAME: ASDFASF24 # echo -n 'password' | base64
  DB_PASSWORD: ADSFADS
